### ISSUE TITLE
逻辑帧的计时器不是主线程,Unity有些方法变量只能在主线程访问,只能避免这样调用嘛

### ISSUE THREAD

**Issue by tianjiuwan** [dudu502/LittleBee#1]

**Comment by tianjiuwan** [comment]
我看你的逻辑帧 更新的逻辑都是在更改数据
继承ActionRenderer的 在MonoBehaviour的Update里面取实体数据更新到GameObject上
只能这样搞嘛

**Comment by dudu502** [comment]
逻辑帧的计时器在一个线程中进行，主线程主要负责显示部分，因此线程中每一逻辑帧数据操作完毕后，对数据进行脏标记处理，主线程中运行的ActionRenderer可以有选择的处理一些变化，我为了考虑加入物理运算以及在战斗结束后客户端也能用于校验战报的完整数据层面上的复盘，因此就要放线程里处理了。

**Comment by dudu502** [comment]
> 我看你的逻辑帧 更新的逻辑都是在更改数据
> 继承ActionRenderer的 在MonoBehaviour的Update里面取实体数据更新到GameObject上
> 只能这样搞嘛

逻辑帧的计时器在一个线程中进行，主线程主要负责显示部分，因此线程中每一逻辑帧数据操作完毕后，对数据进行脏标记处理，主线程中运行的ActionRenderer可以有选择的处理一些变化，我为了考虑加入物理运算以及在战斗结束后客户端也能用于校验战报的完整数据层面上的复盘，因此就要放线程里处理了。
