### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by xiaopizi19** [dudu502/LittleBee#2]
这个工程客户端不能生成entity 有部分脚本missing
麻烦你能看下缺少哪些么

**Comment by dudu502** [comment]
你好 ，这个问题我了解了，我会尽早查看的，谢谢

**Comment by dudu502** [comment]
整个问题找到了，是由于ByteBuffer的position的问题。现在修复了

**Comment by xiaopizi19** [comment]
> 整个问题找到了，是由于ByteBuffer的position的问题。现在修复了

好的 谢谢啦
