### ISSUE TITLE
请教作者一个问题?

### ISSUE THREAD

**Issue by suiyuex** [dudu502/LittleBee#9]
我看大部分帧同步的项目, 逻辑帧间隔都是使用累加的方式计算的.

请问以下两种方式有什么区别吗?

下面是伪代码
```c#
int tickRate = 100;

// 直接使用Thread.sleep方式
Thread.sleep(100);

// 累加时间方式
float timeSinceStart = 0;
timeSinceStart += deltaTime;
int tick = 0;
if(timeSinceStart % tickRate > tick)
{
// tick
tick++;
}
```

**Comment by dudu502** [comment]
你这个例子里帧率是10对吗？每个100毫秒是一帧对吗？
那么你这个时间累计是不准的。你只是把帧数累加了一下，但是无法保证不同设备保持一样的帧率，因为你没有和本地时间做校准。简单地说就是你有两个设备同时开始启动，经过10分钟的运行后你会发现两个设备的帧数有很大差距。
你这个里面的deltaTime也不够精准，需要用到系统DateTime里的Tick。这是最小的时间计数单位

**Comment by suiyuex** [comment]
感谢，受教了

之前认为，帧同步只要保证保证每个逻辑帧执行了操作，就行了

经过十分钟之后，两个设备的帧数不一致， 但是可以确保两个设备都运行到100帧时，两个设备结果是一致的

之前却不知道真实游戏开发中，经过十分钟两个设备的逻辑帧也要保持一致

感谢
